pipeline:

  build:
    image: gradle:5.5.1-jdk8
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    commands:
      - gradle build
  publish:
    image: plugins/github-release
    files:
      - build/libs/kotlin-mf-starter-jvm-*.jar
    checksum:
      - sha256
    secrets: [github_token]
    when:
      event: tag
